package com.mybatis.my.mapper;

import com.mybatis.my.bean.UserRole;
import com.mybatis.my.bean.UserRoleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    int countByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    int deleteByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    List<UserRole> selectByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    int updateByExample(@Param("record") UserRole record, @Param("example") UserRoleExample example);
}