package com.mybatis.my.bean;

public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_permission.id
     *
     * @mbggenerated Wed Sep 04 16:38:51 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_permission.permission
     *
     * @mbggenerated Wed Sep 04 16:38:51 CST 2019
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_permission.url
     *
     * @mbggenerated Wed Sep 04 16:38:51 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_permission.describe
     *
     * @mbggenerated Wed Sep 04 16:38:51 CST 2019
     */
    private String describe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_permission.id
     *
     * @return the value of s_permission.id
     *
     * @mbggenerated Wed Sep 04 16:38:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_permission.id
     *
     * @param id the value for s_permission.id
     *
     * @mbggenerated Wed Sep 04 16:38:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_permission.permission
     *
     * @return the value of s_permission.permission
     *
     * @mbggenerated Wed Sep 04 16:38:51 CST 2019
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_permission.permission
     *
     * @param permission the value for s_permission.permission
     *
     * @mbggenerated Wed Sep 04 16:38:51 CST 2019
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_permission.url
     *
     * @return the value of s_permission.url
     *
     * @mbggenerated Wed Sep 04 16:38:51 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_permission.url
     *
     * @param url the value for s_permission.url
     *
     * @mbggenerated Wed Sep 04 16:38:51 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_permission.describe
     *
     * @return the value of s_permission.describe
     *
     * @mbggenerated Wed Sep 04 16:38:51 CST 2019
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_permission.describe
     *
     * @param describe the value for s_permission.describe
     *
     * @mbggenerated Wed Sep 04 16:38:51 CST 2019
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }
}