package com.mybatis.my.bean;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.id
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.role
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.describe
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    private String describe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.id
     *
     * @return the value of s_role.id
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.id
     *
     * @param id the value for s_role.id
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.role
     *
     * @return the value of s_role.role
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.role
     *
     * @param role the value for s_role.role
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.describe
     *
     * @return the value of s_role.describe
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.describe
     *
     * @param describe the value for s_role.describe
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }
}