package com.mybatis.my.bean;

public class RolePermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role_permission.fk_role_id
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    private Integer fkRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role_permission.fk_permission_id
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    private Integer fkPermissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role_permission.fk_role_id
     *
     * @return the value of s_role_permission.fk_role_id
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    public Integer getFkRoleId() {
        return fkRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role_permission.fk_role_id
     *
     * @param fkRoleId the value for s_role_permission.fk_role_id
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    public void setFkRoleId(Integer fkRoleId) {
        this.fkRoleId = fkRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role_permission.fk_permission_id
     *
     * @return the value of s_role_permission.fk_permission_id
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    public Integer getFkPermissionId() {
        return fkPermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role_permission.fk_permission_id
     *
     * @param fkPermissionId the value for s_role_permission.fk_permission_id
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    public void setFkPermissionId(Integer fkPermissionId) {
        this.fkPermissionId = fkPermissionId;
    }
}