package com.mybatis.my.bean;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_role.fk_user_id
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    private Integer fkUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_role.fk_role_id
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    private Integer fkRoleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_role.fk_user_id
     *
     * @return the value of s_user_role.fk_user_id
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    public Integer getFkUserId() {
        return fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_role.fk_user_id
     *
     * @param fkUserId the value for s_user_role.fk_user_id
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    public void setFkUserId(Integer fkUserId) {
        this.fkUserId = fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_role.fk_role_id
     *
     * @return the value of s_user_role.fk_role_id
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    public Integer getFkRoleId() {
        return fkRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_role.fk_role_id
     *
     * @param fkRoleId the value for s_user_role.fk_role_id
     *
     * @mbggenerated Mon Sep 02 20:59:43 CST 2019
     */
    public void setFkRoleId(Integer fkRoleId) {
        this.fkRoleId = fkRoleId;
    }
}